source 'https://github.com/CocoaPods/Specs.git'

target 'BAColoredIconManager', :exclusive => true do
  pod "BAColoredIconManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BAColoredIconManager", :path => "../"

  
end
